# local 환경
spring:
  config.activate.on-profile: local
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 10001

---
# develop 환경
spring:
  config.activate.on-profile: develop
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 10001