server:
  port: 15051

spring:
  application:
    name: user-service

  config:
    import: "optional:env[.env.user]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: postgresql


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  access:
    expiration: ${ACCESS_EXPIRATION}
  refresh:
    expiration: ${REFRESH_EXPIRATION}
  secret: ${SECRET_KEY}

