services:
  postgres:
    container_name: postgres17-faster
    image: postgres:17
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Seoul
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    entrypoint: [ "bash", "-c", "apt-get update &&
     apt-get install -y postgresql-17-http && 
     psql -U postgres -d postgres -c 'CREATE EXTENSION IF NOT EXISTS http;'"]

  redis:
    image: redis/redis-stack-server
    container_name: redis-server-faster
    restart: always
  #  environment:
 #     REDIS_ARGS: "--requirepass systempass"
    ports:
      - 6379:6379

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-faster
    restart: always
    ports:
      - 9411:9411
volumes:
  postgres-data:
