spring:
  application:
    name: hub-service
  config:
    import:
      - file:.env.hub[.properties]
      - classpath:/properties/base.yml
      - classpath:/properties/datasource.yml
      - classpath:/properties/jpa.yml
      - classpath:/properties/cloud.yml
      - classpath:/properties/directions-api.yml
  profiles:
    group:
      local: local
      test: test
      prod: prod
    active: local