spring:
  application:
    name: hub-service
  config:
    import:
      - file:.env.hub[.properties]
      - classpath:/properties/base.yml
      - classpath:/properties/datasource.yml
      - classpath:/properties/jpa.yml
      - classpath:/properties/cloud.yml
      - classpath:/properties/directions-api.yml
      - classpath:/properties/redis.yml
      - classpath:/properties/zipkin.yml
      - classpath:/properties/resilience4j-retry.yml
  profiles:
    group:
      local: local
      develop: develop
      test: test
      develop: develop
      prod: prod
    active: local