server:
  port: 11001


spring:
  config.activate.on-profile: develop
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: faster

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: ${DEV_ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0
