# local 환경
spring:
  config.activate.on-profile: local
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 11001

---
# test 환경
spring:
  config.activate.on-profile: test
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 11001
