# local 환경
spring:
  config.activate.on-profile: local
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 12001

---
# test 환경
spring:
  config.activate.on-profile: test
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 12002


---
# develop 환경
spring:
  config.activate.on-profile: develop
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 12002