# local 환경
spring:
  config.activate.on-profile: local
management:
  zipkin:
    tracing:
      endpoint: ${LOCAL_ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0


---
# dev 환경
spring:
  config.activate.on-profile: develop
management:
  zipkin:
    tracing:
      endpoint: ${DEV_ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0