spring:
  application:
    name: order-service
  config:
    import:
      - file:.env.order[.properties]
      - classpath:properties/base.yml
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/cloud.yml
      - classpath:properties/zipkin.yml
  profiles:
    group:
      local: local
      develop: develop
      test: test
      prod: prod
    active: local
