server:
  port: 12002

spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: faster
  sql:
    init:
      mode: never
      data-locations: classpath:db/data.sql # db 시작할때 실행시킬 script (더미 데이터 생성)

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      username: default
      password: systempass

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: ${DEV_ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0