spring:
  application:
    name: gateway-service
  config:
    import:
      - file:.env.gateway[.properties]
      - classpath:/properties/base.yml
      - classpath:/properties/datasource.yml
      - classpath:/properties/jpa.yml
      - classpath:/properties/cloud.yml
      - classpath:/properties/gateway-route.yml
      - classpath:/properties/jwt.yml
  profiles:
    group:
      local: local
      test: test
      prod: prod
    active: local







