### GET 업체 정보 조회
GET http://localhost:11002/api/companies/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### GET 업체 검색
GET http://localhost:11002/api/companies?
    company-manager-id={{$random.integer(100)}}&
    search-text={{$random.alphanumeric(8)}}&
    name-search-text={{$random.alphanumeric(8)}}&
    contact-search-text={{$random.alphanumeric(8)}}&
    address-search-text={{$random.alphanumeric(8)}}&
    type-text={{$random.alphanumeric(8)}}

### POST 업체 생성
POST http://localhost:11002/api/companies
Content-Type: application/json
X-User-Id: 5
X-User-Role: ROLE_COMPANY

{
  "hubId": "00000000-0000-0000-0000-000000000001",
  "companyManagerId": 5,
  "name" : "생선도매상",
  "contact": "010-0000-0000",
  "address": "서울시 영등포구 어딘가",
  "type": "SUPPLIER"
}

### PATCH 업체 수정
PATCH http://localhost:11002/api/companies
Content-Type: application/json
X-User-Id: 6
X-User-Role: ROLE_COMPANY

{
  "companyId": "00000000-0000-0000-0000-000000000001",
  "hubId": "00000000-0000-0000-0000-000000000002",
  "name" : "해산물도매상",
  "contact": "010-0000-0000",
  "address": "서울시 영등포구 어딘가"
}

### DELETE 업체 삭제
DELETE http://localhost:11002/api/companies/00000000-0000-0000-0000-000000000002
Content-Type: application/json
X-User-Id: 5
X-User-Role: ROLE_COMPANY

### GET 업체 아이디 기준 내부 업체 정보 조회
GET http://localhost:11002/internal/companies/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### GET 업체 매니저 아이디 기준 내부 업체 정보 조회
GET http://localhost:11002/internal/companies/managers/5
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER