spring:
  application:
    name: delivery
  datasource:
    hikari:
      maximum-pool-size: 20
      # 177초
      max-lifetime: 177000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testDbName
    username:
    password: