server:
  port: 13001
spring:
  application:
    name: delivery-service
  datasource:
    hikari:
      maximum-pool-size: 20
      # 177초
      max-lifetime: 177000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testDbName
    username:
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/