server:
  port: 15050

management:
  zipkin:
    tracing:
      endpoint: ${LOCAL_ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: message-service

  config:
    import:
      - file:.env.message[.properties]

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: ture
        default_schema: faster
    database: postgresql


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

gemini:
  api:
    url: ${GEMINI_API_URL}
  token: ${GEMINI_TOKEN}

slack:
  api:
    url:
      user-list: ${SLACK_USER_LIST_URL}
      open-conversation: ${SLACK_OPEN_CONVERSATION_URL}
      post-message: ${SLACK_POST_MESSAGE_URL}
    token: ${SLACK_BOT_TOKEN}

