### 서울특별시 센터 등록
POST http://localhost:12001/api/hubs
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "name": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": "127.1239062",
  "longitude": "37.4741540"
}

### 허브 단건 조회
GET http://localhost:12001/api/hubs/443a1c68-8dab-4a63-9bda-86e05bfecece

### 허브 단건 수정
PATCH http://localhost:12001/api/hubs/0815cff1-4c8e-4252-8e75-269875bce8ba
Content-Type: application/json
X-User-Id: 3
X-User-Role: ROLE_MASTER

{
  "name": "서울특별시 센터1",
  "address": "서울특별시 송파구 송파대로 551",
  "latitude": "127.12390621",
  "longitude": "37.47415401"
}

### 허브 단건 삭제
DELETE http://localhost:12001/api/hubs/5866d23b-b6dd-4d34-ae61-eec4119d1aba
X-User-Id: 1
X-User-Role: ROLE_MASTER

### 경로 조회
GET http://localhost:12001/internal/hubs/paths?source_hub_id=ab466b9f-1a1f-480e-a43d-7b466fd94cf3&destination_hub_id=85f02000-6bc6-4210-88a6-c0f6998072dd