### 서울특별시 센터 등록
POST http://localhost:12001/api/hubs
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "name": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": "127.1239062",
  "longitude": "37.4741540"
}

### 허브 단건 조회
GET http://localhost:12001/api/hubs/443a1c68-8dab-4a63-9bda-86e05bfecece

### 허브 단건 삭제
DELETE http://localhost:12001/api/hubs/5866d23b-b6dd-4d34-ae61-eec4119d1aba
X-User-Id: 1
X-User-Role: ROLE_MASTER