# local 환경
spring:
  config.activate.on-profile: local
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    #      default_batch_fetch_size: 10
    generate-ddl: true

---
# dev 환경
spring:
  config.activate.on-profile: develop
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false