### GET 상품 단건 조회
GET http://localhost:11001/api/products/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### DELETE 상품 단건 삭제
DELETE http://localhost:11001/api/products/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### PATCH 상품 수정
PATCH http://localhost:11001/api/products/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "name" : "쪽파 20단",
  "price": 10000,
  "quantity": 1000,
  "description": "대파에서 쪽파로 변경합니다."
}

### POST 상품 생성
POST http://localhost:11001/api/products
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "hubId": "00000000-0000-0000-0000-000000000001",
  "companyId": "00000000-0000-0000-0000-000000000001",
  "companyName": "대파도매상",
  "name" : "양파 20묶음",
  "price": 10000,
  "quantity": 10000,
  "description": "양파도 팝니다."
}