### GET 주문 검색 조회
GET http://localhost:12002/api/orders?min-total-price=1000
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### GET 주문 단건 조회
GET http://localhost:12002/api/orders/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### DELETE 주문 단건 삭제
DELETE http://localhost:12002/api/orders/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### PATCH 주문 상태 취소 변경
PATCH http://localhost:12002/api/orders/00000000-0000-0000-0000-000000000001/cancel
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### POST 주문 생성
POST http://localhost:12002/api/orders
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "supplierCompanyId" : "00000000-0000-0000-0000-000000000001",
  "receivingCompanyId" : "00000000-0000-0000-0000-000000000001",
  "supplierCompanyName" : "공급업체명",
  "receivingCompanyName" : "수령업체명",
  "receivingCompanyAddress" : "수령 업체 주소",
  "receivingCompanyContact" : "010-0000-0000",
  "request" : "10일 오전 10시까지 배송해주세요.",
  "orderItems" : [{
    "productId" : "00000000-0000-0000-0000-000000000001",
    "name" : "대파 10단",
    "quantity" : 3,
    "price": 10000
  }, {
    "productId" : "00000000-0000-0000-0000-000000000002",
    "name" : "상추 10묶음",
    "quantity" : 3,
    "price": 10000
  }, {
    "productId" : "00000000-0000-0000-0000-000000000003",
    "name" : "배추 10포기",
    "quantity" : 3,
    "price": 10000
  }, {
    "productId" : "00000000-0000-0000-0000-000000000004",
    "name" : "미나리 10단",
    "quantity" : 3,
    "price": 10000
  }]
}

### PATCH 내부 주문 상태 확정 변경
PATCH http://localhost:12002/internal/orders/00000000-0000-0000-0000-000000000001/confirm
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

### PATCH 내부 주문 상태 변경
PATCH http://localhost:12002/internal/orders/00000000-0000-0000-0000-000000000001/status
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER

{
  "status": "CONFIRMED"
}

### GET 주문 내부 단건 조회
GET http://localhost:12002/internal/orders/00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 1
X-User-Role: ROLE_MASTER