spring:
  application:
    name: company-service
  config:
    import:
      - file:.env.company[.properties]
      - classpath:/properties/base.yml
      - classpath:/properties/datasource.yml
      - classpath:/properties/jpa.yml
      - classpath:/properties/cloud.yml
  profiles:
    group:
      local: local
      test: test
      prod: prod
    active: local
